### ISSUE TITLE
server crashing on vote claim

### ISSUE THREAD

**Issue by Ironic8b498** [teozfrank/UltimateVotes#33]
Spigot 1.15.2 and sometimes when players run claim all command I get this error and server crashes https://paste.helpch.at/sigufemita.md
my crash report
https://paste.helpch.at/zivihaqopo.rb

**Comment by teozfrank** [comment]
Could you please list the commands that are ran on giving rewards?
Can you provide your full plugin list?
Can you possibly do a timings report?

The server seems to be crashing on ticking the world, It does not throw any exceptions or show anything in the crash report relating to ultimatevotes at all.

net.minecraft.server.v1_15_R1.ReportedException: Exception ticking world

It may possibly be a bug with 1.15 but I am open to look into this further as soon as you provide me more detail. Thanks.

**Comment by teozfrank** [comment]
Just a follow up:

The timings of the command ran and the crash are quite some time apart so I am pretty sure they are not related to UltimateVotes unless you can explain otherwise. If the timings were close then maybe it might have something to do with it. The fact that the server crashes **several hours after** the last ultimatevotes commmand was executed points me towards another issue you have with the server not related to ultimatevotes.

![image](https://user-images.githubusercontent.com/3265598/76859776-dd243a00-6851-11ea-81b0-5ee8b59afd2b.png)

**Comment by teozfrank** [comment]
closed as no response made, if you still have this issue please re-open a new issue.
