### ISSUE TITLE
Players getting over 5000 vote rewards

### ISSUE THREAD

**Issue by Pixiio** [teozfrank/UltimateVotes#5]
Hi.

Yesterday our users that were voting were getting over 5000 rewards. That gave alot of free stuff to them, luckily we were fast. This is the error: http://pastebin.com/Ygiy20Ge

Looks like we're getting blocked out of the Mojang api because of too many request.., right?

Thanks!

**Comment by teozfrank** [comment]
Yes it seems that way, that usually shouldnt happen, those uuid's look strange being passed to mojang, is it someone trying to abuse the voting system because it sure looks like it. 

lGnMaje3p08ipApw from minecraftserverlijst_nl with IP 127.0.0.2. 

That username is fake by the looks of it.

Is it test votes or actual votes?

**Comment by teozfrank** [comment]
Sorry accidently clicked close.

**Comment by Pixiio** [comment]
I might have found the error. In one of the servers I accidentally uploaded the BungeeCord version in combination with the normal version. The UV-BungeeCord config was not uploaded in the server so I'm not sure if it can cause this bug?

**Comment by teozfrank** [comment]
No it wouldnt, the bungeecord version just wouldnt start up on the spigot server. Could you show me the full log of bungee for the last day?

**Comment by teozfrank** [comment]
Closed as no response given, please re-open a new issue if this issue still persists, thanks.
